### ISSUE TITLE
Failed to set NVRAM property

### ISSUE THREAD

**Issue by TobiasBouma** [daliansky/XiaoMi-Pro#157] opened 2019-02-24 22:42 UTC
Mentioning a potential issue.

So I tried to install High Sierra using the guide and I'm getting an NVRAM issue in the installer (as seen from the logs). Also, idling while the OS X Installer is running sometimes leads to kernel panic and random reboots. Attempting to install High Sierra on my ssd gives me the following messages (I typed this over from screenshots off my mobile phone so it's a bit incomplete, let me know if something is not clear):

osinstallersetupd[561]: OSISDownloadOperation: totalEstimate=397.00000, significantDownload=1
osinstallersetupd[561]: OSISDownloadOperation: No Ial update found on http://swscan...
osinstallersetupd[561]: OSISDownloadOperation: No native mechanism to verify InstallESD.dmg
osinstallersetupd[561]: OSISDownloadOperation: No native mechanism to verify AppleDiagonstics.dmg
osinstallersetupd[561]: OSISDownloadOperation: No native mechanism to verify AppleDiagonstics.chunklist
osinstallersetupd[561]: OSISDownloadOperation: No native mechanism to verify InstallInfo.plist
...
osinstallersetupd[561]: Personalization is not required for the running system
osinstallersetupd[561]: Warning: couldn't find on-disk package for specificier: <PKPackage...
osinstallersetupd[561]: Operation queue succeeded
osishelperd[578]: isModernOS = 1
Installer Progress[180]: IASClearInstallProgress: Clearing Registry
Installer Progress[180]: IASSetCurrentInstallPhaselist: phases set to (
Installer Progress[180]: IASSetCurrentInstallPhase: Current phase name set to "Boot 1"
Installer Progress[180]: IASSetCurrentInstallPhaselist: phases set to (
Installer Progress[180]: IASSetCurrentInstallPhaselist: phases set to (
Installer Progress[180]: IASSetCurrentInstallPhaselist: phases set to (
Installer Progress[180]: IASSetCurrentInstallPhaselist: phases set to (
Installer Progress[180]: IASSetCurrentInstallPhaselist: phases set to (
Installer Progress[180]: IASSetCurrentInstallPhaselist: phases set to (
osishelperd[578]: Failed to set NVRAM property.
osinstallersetupd[561]: Target is not convertible to APFS: You may not install to this ...
osishelperd[578]: Failed to prep /Volumes/OS X Base System 1 for brtool
opendirectoryd[186]: [default] Failed to open file <private> [2: No such file or directory]

Does PM981 lead to the above issues? I'm getting them also on non PM981 drives.. like a USB stick, but this install failing may have a different cause. Also tried different methods for creating the USB stick, like diskmaker X on a native mac or the "from scratch using only windows" solution that I also mentioned in https://www.insanelymac.com/forum/topic/337740-issues-installing-high-sierra-on-xiaomi-mi-notebook-pro-gtx/?tab=comments#comment-2665230. I also tried installing from different USB sticks (I even bought a brand new one just to get it going...). Even tried formatting the volumes target to OOS install using different file system formats (every single kind of APFS or Apple Extended file systems, and yes I did initially try the Journaled one as recommended by most people).

Any suggestions?

**Comment by stevezhengshiqi** [comment] 2019-02-24 23:32
Hi, the error log above is exactly caused by PM981. It will be removed if you change a SSD.

**Comment by TobiasBouma** [comment] 2019-02-25 13:04
Many thanks. I have now succesfully installed macOS.

But: my PC keeps rebooting randomly now. I can stay on desktop for perhaps a minute or two before this happens.

**Comment by stevezhengshiqi** [comment] 2019-02-25 15:33
It’s a common issue for macOS on PM981, and you may discover the reason that people don’t recommend to install macOS on PM981. 
As README says, you need another supported SSD.

**Comment by stevezhengshiqi** [comment] 2019-02-25 15:34
I will close this issue since it’s a duplicate problem for PM981 and currently has no solutions.

**Closed by stevezhengshiqi** 2019-02-25 15:34 UTC
